apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
        - name: httpserver
          image: wujiangxingzhe/httpserver:v0.2
          imagePullPolicy: IfNotPresent
          ports: 
          - protocol: TCP
            containerPort: 8080
            hostPort: 8080
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 1
          readinessProbe:
            httpGet: 
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 2
            successThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          resources:
            limits:
              cpu: "500m"
              memory: "128Mi"
            requests:
              cpu: "250m"
              memory: "64Mi"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "pkill -SIGUSR1 httpserver"]
          volumeMounts:
            - name: httpserver-logs
              mountPath: /opt
      volumes:
        - name: httpserver-logs
          hostPath: 
            path: /var/log